services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    container_name: api
    depends_on:
      - postgres_db
      - rabbitmq
      - celery
    volumes:
      - .:/app
    
    command:
      sh -c "
      uv run python -m alembic upgrade head &&
      uv run uvicorn main:app --host 0.0.0.0 --port 8000 --reload
      "

  postgres_db:
    image: postgres:latest
    container_name: postgres
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  
  rabbitmq:
    image: rabbitmq:3-management-alpine
    hostname: rabbitmq
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    
  celery:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: celery
    command: uv run celery -A core.celery_app worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - rabbitmq
  
  maildev:
    image: maildev/maildev
    environment:
      - TZ=Europe/Moscow
      - MAILDEV_WEB_PORT=1080
      - MAILDEV_SMTP_PORT=1025
    ports:
      - "8080:1080"
      - "1025:1025"
    logging:
      driver: "json-file"
      options:
        max-size: "1m"

volumes:
  pgdata:
  rabbitmq-data:

