"""edit initial revision

Revision ID: eba1f6480973
Revises: f766a9c380ff
Create Date: 2025-08-27 10:29:21.103820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eba1f6480973'
down_revision: Union[str, Sequence[str], None] = 'f766a9c380ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notifications', 'message_text',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notifications', 'message_text',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
